### ISSUE TITLE
Try to fix the CI build

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/fs2-rabbit#11]
There's a problem with the dependency of Apache Qpid Broker and Logback. I've tried a few different combinations but they all failed. However, with the current configuration runs locally without problems, don't know how to fix the problem exactly.

```
[info] Exception encountered when attempting to run a suite with class name: com.github.gvolpe.fs2rabbit.Fs2RabbitSpec *** ABORTED ***
[info]   java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
[info]   at org.apache.qpid.server.Broker$1.run(Broker.java:147)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at javax.security.auth.Subject.doAs(Subject.java:422)
[info]   at org.apache.qpid.server.Broker.startup(Broker.java:142)
[info]   at com.github.gvolpe.fs2rabbit.embedded.EmbeddedAmqpBroker$.start(EmbeddedAmqpBroker.scala:16)
[info]   at com.github.gvolpe.fs2rabbit.Fs2RabbitSpec.beforeAll(Fs2RabbitSpec.scala:19)
[info]   at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info]   at com.github.gvolpe.fs2rabbit.Fs2RabbitSpec.beforeAll(Fs2RabbitSpec.scala:14)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
[info]   at com.github.gvolpe.fs2rabbit.Fs2RabbitSpec.run(Fs2RabbitSpec.scala:14)
```

**Comment by gvolpe** [comment]
It seems to be a bug in the Qpid library. Issue reported: https://issues.apache.org/jira/browse/QPID-7824
