### ISSUE TITLE
Consuming a message throws NullPointerException if AMQP.BasicProperties.getHeaders is null

### ISSUE THREAD

**Issue by akreuzer** [gvolpe/fs2-rabbit#40]
The `defaultConsumer` in `UnderlyingAmqpClient` does not handle the case when `properties.getHeaders` in `handleDelivery` returns `null`.
In this case an exception like the following is thrown.
```
(ERROR) com.rabbitmq.client.impl.ForgivingExceptionHandler: Consumer com.github.gvolpe.fs2rabbit.UnderlyingAmqpClient$$anon$1@1a3324af (amq.ctag-Grspu7yRG6e2rQ8J-8NqnA) method handleDelivery for channel AMQChannel(amqp://guest@xxx:5672/,1) threw an exception for channel AMQChannel(amqp://guest@xxx:5672/,1) java.lang.NullPointerException
	at com.github.gvolpe.fs2rabbit.model$AmqpProperties$.from(model.scala:67)
	at com.github.gvolpe.fs2rabbit.UnderlyingAmqpClient$$anon$1.handleDelivery(Fs2Rabbit.scala:51)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

To create a such a message I used `amqp-publish` in the following way `amqp-publish -u amqp://guest:guest@xxx:5672 -e "" -r daQ`
The `AMQP.BasicProperties` I got with this were as follows.
```
#contentHeader<basic>(content-type=null, content-encoding=null, headers=null, delivery-mode=1, priority=null, correlation-id=null, reply-to=null, expiration=null, message-id=null, timestamp=null, type=null, user-id=null, app-id=null, cluster-id=null)
```

**Comment by gvolpe** [comment]
Hi @akreuzer , thanks for reporting! I'm replying to your PR, check it out!
