### ISSUE TITLE
Unsafe arguments

### ISSUE THREAD

**Issue by insdami** [gvolpe/fs2-rabbit#50]
Arguments that are passed through `QueueConfig` could potentially throw a run time exception 
```
ERROR c.g.gvolpe.fs2rabbit.instances.log$ - invalid value in table
java.lang.IllegalArgumentException: invalid value in table
	at com.rabbitmq.client.impl.Frame.fieldValueSize(Frame.java:310) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.Frame.tableSize(Frame.java:250) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.ValueWriter.writeTable(ValueWriter.java:119) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.MethodArgumentWriter.writeTable(MethodArgumentWriter.java:138) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQImpl$Queue$Declare.writeArgumentsTo(AMQImpl.java:1496) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.Method.toFrame(Method.java:85) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQCommand.transmit(AMQCommand.java:104) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:363) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQChannel.quiescingTransmit(AMQChannel.java:345) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQChannel.quiescingRpc(AMQChannel.java:280) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:271) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:233) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:128) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:948) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:333) ~[amqp-client-4.1.0.jar:4.1.0]
	at com.github.gvolpe.fs2rabbit.interpreter.AmqpClientStream.$anonfun$declareQueue$1(AmqpClientStream.scala:138) ~[classes/:na]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library.jar:na]
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:74) ~[cats-effect_2.12-0.8.jar:0.8]
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34) ~[cats-effect_2.12-0.8.jar:0.8]
	at cats.effect.IO.unsafeRunAsync(IO.scala:191) ~[cats-effect_2.12-0.8.jar:0.8]
	at cats.effect.IO.$anonfun$runAsync$1(IO.scala:150) ~[cats-effect_2.12-0.8.jar:0.8]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library.jar:na]
	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:154) ~[cats-effect_2.12-0.8.jar:0.8]
	at cats.effect.IO.unsafeRunTimed(IO.scala:220) ~[cats-effect_2.12-0.8.jar:0.8]
	at cats.effect.IO.unsafeRunSync(IO.scala:173) ~[cats-effect_2.12-0.8.jar:0.8]
	at com.github.gvolpe.fs2rabbit.examples.IOApp.main(IOApp.scala:23) ~[classes/:na]
	at com.github.gvolpe.fs2rabbit.examples.IOApp.main$(IOApp.scala:23) ~[classes/:na]
	at com.github.gvolpe.fs2rabbit.examples.IOAckerConsumer$.main(IOAckerConsumer.scala:26) ~[classes/:na]
	at com.github.gvolpe.fs2rabbit.examples.IOAckerConsumer.main(IOAckerConsumer.scala) ~[classes/:na]
```
Maybe we can create existential types to validate types at compile time using this as a reference
https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/Frame.java#L256

**Comment by gvolpe** [comment]
Agree that this should be improved. The Java client is terrible. Feel free to share your ideas or directly create a PR. At the moment there's no other work going on in other branches and there's not going to be at least this week.

**Comment by gvolpe** [comment]
Hey @insdami , I want to start looking into a solution for this issue. Do you remember exactly how to reproduce this issue? We now have `DeclarationQueueConfig`.

**Comment by insdami** [comment]
@gvolpe If the config contains `arguments` not supported by https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/Frame.java#L256 you gonna get an error like the above one. At the moment you can do that because `arguments` is `Map[String, AnyRef]`
```scala
DeclarationQueueConfig(..., arguments = Map("anArgument" -> MyCrazyValue("yolo"))
```

**Comment by gvolpe** [comment]
Thanks! Yeah this is spread across all the functionality of the Java Client, will see what we can do about it...
